# Generated by Django 4.0.6 on 2022-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_text_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_preview',
            field=models.TextField(verbose_name='Текст-превью'),
        ),
    ]
