# Generated by Django 4.0.6 on 2022-08-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productimages_product_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='image',
            field=models.ImageField(null=True, upload_to='blog/category', verbose_name='Зображення'),
        ),
    ]
