# Generated by Django 4.0.6 on 2022-08-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='images', through='catalog.ProductImages', to='catalog.product', verbose_name='Зображення'),
        ),
    ]
