# Generated by Django 4.0.6 on 2022-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='catalog/product-images', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(null=True, upload_to='catalog/product-images', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основне зображення'),
        ),
    ]
