# Generated by Django 4.0.6 on 2022-08-15 17:17

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/article', verbose_name='Зображеня'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
