# Generated by Django 4.0.6 on 2022-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productimages_image_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
